from app.extensions import db
from app.models.product import Product
from app.models.product_category import ProductCategory

PRODUCTS_DEFAULT = [
    ["Äpfel","Obst"],
    ["Birnen","Obst"],
    ["Zitrone","Obst"],
    ["Khaki","Obst"],
    ["Heidelbeeren","Obst"],
    ["Himbeeren","Obst"],
    ["Brombeeren","Obst"],
    ["Mandarinen","Obst"],
    ["Bananen","Obst"],
    ["Ananas","Obst"],
    ["Honigmelone","Obst"],
    ["Wassermelone","Obst"],
    ["Mango","Obst"],
    ["Orangen","Obst"],
    ["Pfirsiche","Obst"],
    ["Nektarinen","Obst"],
    ["Feldsalat","Gemüse"],
    ["Kopfsalat","Gemüse"],
    ["Karotten","Gemüse"],
    ["Gurke","Gemüse"],
    ["Zucchini","Gemüse"],
    ["Rosenkohl","Gemüse"],
    ["Kohl","Gemüse"],
    ["Tomaten","Gemüse"],
    ["Zwiebeln","Gemüse"],
    ["Kartoffeln","Gemüse"],
    ["Brokkoli","Gemüse"],
    ["Blumenkohl","Gemüse"],
    ["Frühlingszwiebeln","Gemüse"],
    ["Suppengrün","Gemüse"],
    ["Bok Choi","Gemüse"],
    ["Paprika","Gemüse"],
    ["Lauch","Gemüse"],
    ["Knollensellerie","Gemüse"],
    ["Kürbis","Gemüse"],
    ["Knoblauch","Gewürze"],
    ["Ingwer","Gewürze"],
    ["Mais","Hülsenfrüchte"],
    ["Erbsen","Hülsenfrüchte"],
    ["Kidneybohnen","Hülsenfrüchte"],
    ["Sonnenblumenhack","Ersatzprodukte"],
    ["Sonnenblumenkerne","Getreide"],
    ["Batterien","Elektronik"],
    ["Pastinaken","Gemüse"],
    ["Spargel","Gemüse"],
    ["Suppe","Fertigprodukte"],
    ["Eintopf","Fertigprodukte"],
    ["Reis","Getreide"],
    ["Kartoffelrösti","Fertigprodukte"],
    ["TK-Pizza","Fertigprodukte"],
    ["Frühlingsrollen","Fertigprodukte"],
    ["Eis","Süßigkeiten"],
    ["Haferflocken","Getreide"],
    ["Tomaten (passiert)","Gemüse"],
    ["Tomaten (gestückelt)","Gemüse"],
    ["Nudeln","Teigwaren"],
    ["Pesto","Fertigprodukte"],
    ["Schupfnudeln","Fertigprodukte"],
    ["Gnocchi","Fertigprodukte"],
    ["Quinoa","Getreide"],
    ["Wraps","Teigwaren"],
    ["Knödel","Fertigprodukte"],
    ["Rote Bete","Gemüse"],
    ["Ahornsirup","Süßungsmittel"],
    ["Petersilie","Gewürze"],
    ["Basilikum","Gewürze"],
    ["Oregano","Gewürze"],
    ["Gemüseaufstrich","Aufstrich"],
    ["Preiselbeeren","Aufstrich"],
    ["Marmelade","Aufstrich"],
    ["Tomatensoße","Fertigprodukte"],
    ["Frischkäse","Aufstrich"],
    ["Mascarpone","Milchprodukte"],
    ["Eier","Tierprodukte"],
    ["Butter","Milchprodukte"],
    ["Schmand","Milchprodukte"],
    ["Honig","Aufstrich"],
    ["Sonnenblumenöl","Öl"],
    ["Mehl","Getreideprodukte"],
    ["Haselnüsse (gemahlen)","Nüsse"],
    ["Haselnüsse (gehackt)","Nüsse"],
    ["Haselnüsse (gehobelt)","Nüsse"],
    ["Mandeln (gemahlen)","Nüsse"],
    ["Mandeln (gehackt)","Nüsse"],
    ["Mandeln (gehobelt)","Nüsse"],
    ["Zucker","Süßungsmittel"],
    ["Vanillezucker","Süßungsmittel"],
    ["Puderzucker","Süßungsmittel"],
    ["Kokosraspeln","Nüsse"],
    ["Speisestärke","Getreideprodukte"],
    ["Grieß","Getreide"],
    ["Muskatnuss","Gewürze"],
    ["Semmelbrösel","Getreideprodukte"],
    ["Salz","Gewürze"],
    ["Pfeffer","Gewürze"],
    ["Vanillepudding-Pulver","Fertigprodukte"],
    ["Krokant","Süßungsmittel"],
    ["Gouda","Milchprodukte"],
    ["Cheddar","Milchprodukte"],
    ["Parmesan","Milchprodukte"],
    ["Mozzarella","Milchprodukte"],
    ["Toilettenpapier","Hygieneprodukte"],
    ["Tampons","Hygieneprodukte"],
    ["Taschentücher","Hygieneprodukte"],
    ["Einlagen","Hygieneprodukte"],
    ["Gemüsebrühe","Fertigprodukte"],
    ["Zitronensaft","Getränke"],
    ["Kokosmilch","Ersatzprodukte"],
    ["Currypulver","Gewürze"],
    ["Currypaste","Gewürze"],
    ["Sojasoße","Gewürze"],
    ["Apfelmuß","Obst"],
    ["Balsamico-Essig","Gewürze"],
    ["Zuckerschoten","Gemüse"],
    ["Tofu","Ersatzprodukte"],
    ["Brot","Backwaren"],
    ["Wurst","Fleisch"],
    ["Hefe","Sonstiges"],
    ["Sahne","Milchprodukte"],
    ["Zahnpasta","Hygieneprodukte"],
    ["Zahnbürste","Haushaltsprodukte"],
    ["Salzstangen","Snacks"],
    ["Kekse","Süßigkeiten"],
    ["Kakao","Süßigkeiten"],
    ["Baumkuchen","Süßigkeiten"],
    ["Chips","Snacks"],
    ["Nachos","Snacks"],
    ["Asia-Nudeln","Teigwaren"],
    ["Senf","Gewürze"],
    ["Spülmittel","Haushaltsprodukte"],
    ["Waschmittel","Haushaltsprodukte"],
    ["Shampoo","Hygieneprodukte"],
    ["Duschgel","Hygieneprodukte"],
    ["Spülung","Hygieneprodukte"],
    ["Wattestäbchen","Haushaltsprodukte"],
    ["Seife","Haushaltsprodukte"],
    ["Schwamm","Haushaltsprodukte"],
    ["Lippenpflege","Hygieneprodukte"],
    ["Mineralwasser","Getränke"],
    ["Wein","Getränke"],
    ["Tee","Getränke"],
    ["Saft","Getränke"],
    ["Kaffee","Getränke"],
    ["Joghurt","Milchprodukte"],
    ["Soja-Joghurt","Ersatzprodukte"],
    ["Milch","Milchprodukte"],
    ["Haferdrink","Ersatzprodukte"],
    ["Dinkel (gepufft)","Müsli"],
    ["Backpapier","Haushaltsprodukte"],
    ["Mülltüten","Haushaltsprodukte"],
    ["Klarspüler","Haushaltsprodukte"],
    ["Rasierklingen","Haushaltsprodukte"],
    ["Kondome","Haushaltsprodukte"],
]

def add_products(products, clear=False):

    if clear:
        db.session.query(Product).delete()

    objs = []
    for p in products:
        if "name" in p and "category" in p:
            name = p["name"]
            category = p["category"]
        elif len(p) >= 2:
            name = p[0]
            category = p[1]

        cat = db.session.execute(db.select(ProductCategory).filter_by(name=category)).scalar()
        if cat is None:
            cat = ProductCategory(name=category)
            db.session.add(cat)

        if name is not None and cat is not None:
            objs.append(Product(name=name, category_id=cat.id))

    db.session.add_all(objs)
    db.session.commit()

if __name__ == "__main__":
    add_products(PRODUCTS_DEFAULT, True)
