"""added unique constraints

Revision ID: 7067182e5129
Revises: 4191af018f0a
Create Date: 2023-05-21 16:33:02.299233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7067182e5129'
down_revision = '4191af018f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand_products', schema=None) as batch_op:
        batch_op.drop_constraint('uq_brand_products_name', type_='unique')
        batch_op.create_unique_constraint('unique_name_product', ['name', 'product_id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('uq_products_name', type_='unique')
        batch_op.create_unique_constraint('unique_name_category', ['name', 'category_id'])

    with op.batch_alter_table('receipt_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_receipt_items_product_id_products'), 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_receipt_items_product_id_products'), type_='foreignkey')
        batch_op.drop_column('product_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('unique_name_category', type_='unique')
        batch_op.create_unique_constraint('uq_products_name', ['name'])

    with op.batch_alter_table('brand_products', schema=None) as batch_op:
        batch_op.drop_constraint('unique_name_product', type_='unique')
        batch_op.create_unique_constraint('uq_brand_products_name', ['name'])

    # ### end Alembic commands ###
