"""cascade delete

Revision ID: f1d74a17eed0
Revises: 7067182e5129
Create Date: 2023-05-21 17:55:24.389857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d74a17eed0'
down_revision = '7067182e5129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand_products', schema=None) as batch_op:
        # batch_op.drop_constraint('fk_brand_products_product_id_products', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_brand_products_product_id_products'), 'products', ['product_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('products', schema=None) as batch_op:
        # batch_op.drop_constraint('fk_products_category_id_product_categories', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_products_category_id_product_categories'), 'product_categories', ['category_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('receipt_items', schema=None) as batch_op:
        # batch_op.drop_constraint('fk_receipt_items_receipt_id_receipts', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_receipt_items_receipt_id_receipts'), 'receipts', ['receipt_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_receipts_expense_id_expenses', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_receipts_expense_id_expenses'), 'expenses', ['expense_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_receipts_expense_id_expenses'), type_='foreignkey')
        batch_op.create_foreign_key('fk_receipts_expense_id_expenses', 'expenses', ['expense_id'], ['id'])

    with op.batch_alter_table('receipt_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_receipt_items_receipt_id_receipts'), type_='foreignkey')
        batch_op.create_foreign_key('fk_receipt_items_receipt_id_receipts', 'receipts', ['receipt_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_products_category_id_product_categories'), type_='foreignkey')
        batch_op.create_foreign_key('fk_products_category_id_product_categories', 'product_categories', ['category_id'], ['id'])

    with op.batch_alter_table('brand_products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_brand_products_product_id_products'), type_='foreignkey')
        batch_op.create_foreign_key('fk_brand_products_product_id_products', 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###
